const NETWORK="homestead"
const URL= null
const BLOCKSTART=0 
const RERUNTIME=180000
const GASPRICE=20000000000
const ERASE_DATABASE_ON_SYNC=false
const TIMEZONE = "America/Toronto"
const PRUNING = true
const EXCHANGE_ADDRESSES =  ["0xF2d5cBa15c8367dd016FC9c4711443e61c7d95A6"]


module.exports = {
    NETWORK, 
    URL,
    BLOCKSTART, 
    RERUNTIME, 
    GASPRICE, 
    ERASE_DATABASE_ON_SYNC,
    TIMEZONE,
    PRUNING,
    EXCHANGE_ADDRESSES
}