const NETWORK="rinkeby"
const URL= null
const BLOCKSTART=0 
const RERUNTIME=180000
const GASPRICE=2000000000
const ERASE_DATABASE_ON_SYNC=false
const TIMEZONE = "America/Toronto"
const PRUNING = true
const EXCHANGE_ADDRESSES =  ["0x4B757b12659c5f364C2d05c08165D2EB45F4Cf5C"]


module.exports = {
    NETWORK, 
    URL,
    BLOCKSTART, 
    RERUNTIME, 
    GASPRICE, 
    ERASE_DATABASE_ON_SYNC,
    TIMEZONE,
    PRUNING,
    EXCHANGE_ADDRESSES
}